services:
  # Django backend service
  - type: web
    name: optiethic-backend
    runtime: python
    rootDir: ethicsupply-backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ethicsupply.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://optiethic-frontend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: optiethic-db
          property: connectionString

  # React frontend as a static site
  - type: web
    name: optiethic-frontend
    runtime: static
    rootDir: ethicsupply-frontend
    buildCommand: yarn install && VITE_SKIP_TS_CHECK=true yarn build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://optiethic-backend.onrender.com/api
      - key: VITE_ENABLE_MOCK_DATA
        value: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: optiethic-db
    databaseName: optiethic
    plan: free
