services:
  # Backend service
  - type: web
    name: optiethic-backend
    runtime: node
    rootDir: ethicsupply-node-backend
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ALLOWED_ORIGINS
        value: https://optiethic-frontend.onrender.com,https://optisupply-frontend.render.com

  # React frontend as a static site
  - type: web
    name: optiethic-frontend
    runtime: static
    rootDir: ethicsupply-frontend
    buildCommand: ./build.sh
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: VITE_API_URL
        value: https://optiethic-backend.onrender.com/api
      - key: VITE_ENABLE_MOCK_DATA
        value: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: optiethic-db
    databaseName: optiethic
    plan: free
