services:
  # React frontend as a static site
  - type: web
    name: optiethic-frontend
    runtime: static
    buildCommand: |
      # Remove any existing package-lock.json
      rm -f package-lock.json
      # Install dependencies
      yarn install --network-timeout 300000
      # Build the application
      yarn build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://optiethic-backend.onrender.com/api
      - key: VITE_ENABLE_MOCK_DATA
        value: false
      - key: NODE_VERSION
        value: 18.17.0
      - key: VITE_LEAFLET_URL
        value: https://unpkg.com/leaflet@1.9.4/dist/leaflet.css
      - key: VITE_LEAFLET_SCRIPT
        value: https://unpkg.com/leaflet@1.9.4/dist/leaflet.js
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
