services:
  # React frontend as a static site
  - type: web
    name: optiethic-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://optiethic-backend.onrender.com/api
      - key: VITE_ENABLE_MOCK_DATA
        value: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
