/**
 * Shared synthetic suppliers for dev / Vercel mock / Render fallback.
 * Field scales: pillar scores 0–100; KPIs 0–1 where indicated; renewable % 0–100.
 */
module.exports = [
  {
    _id: "67f7fc9e5eed05575d0586c4",
    id: 1,
    name: "Mock Supplier 1",
    country: "USA",
    industry: "Electronics",
    ethical_score: 85,
    co2_emissions: 12.5,
    delivery_efficiency: 0.92,
    wage_fairness: 0.78,
    human_rights_index: 0.85,
    waste_management_score: 0.74,
    environmental_score: 54,
    social_score: 72,
    governance_score: 82,
    community_engagement: 0.76,
    energy_efficiency: 0.74,
    renewable_energy_percent: 28,
    pollution_control: 0.72,
    diversity_inclusion_score: 0.8,
    worker_safety: 0.82,
    transparency_score: 0.78,
    corruption_risk: 0.55,
    board_diversity: 0.74,
    ethics_program: 0.8,
    compliance_systems: 0.82,
    quality_control_score: 0.86,
    supplier_diversity: 0.73,
    traceability: 0.77,
  },
  {
    _id: "67f7fddb5eed05575d0586df",
    id: 2,
    name: "Mock Supplier 2",
    country: "Canada",
    industry: "Consumer Goods",
    ethical_score: 72,
    co2_emissions: 8.3,
    delivery_efficiency: 0.89,
    wage_fairness: 0.94,
    human_rights_index: 0.92,
    waste_management_score: 0.88,
    environmental_score: 33,
    social_score: 81,
    governance_score: 71,
    community_engagement: 0.88,
    energy_efficiency: 0.71,
    renewable_energy_percent: 22,
    pollution_control: 0.66,
    diversity_inclusion_score: 0.9,
    worker_safety: 0.88,
    transparency_score: 0.74,
    corruption_risk: 0.62,
    board_diversity: 0.71,
    ethics_program: 0.76,
    compliance_systems: 0.78,
    quality_control_score: 0.82,
    supplier_diversity: 0.7,
    traceability: 0.68,
  },
  {
    _id: "67f7fddb5eed05575d0586e0",
    id: 3,
    name: "Mock Supplier 3",
    country: "Germany",
    industry: "Automotive",
    ethical_score: 93,
    co2_emissions: 17.2,
    delivery_efficiency: 0.94,
    wage_fairness: 0.94,
    human_rights_index: 0.91,
    waste_management_score: 0.89,
    environmental_score: 87,
    social_score: 91,
    governance_score: 57,
    community_engagement: 0.89,
    energy_efficiency: 0.87,
    renewable_energy_percent: 48,
    pollution_control: 0.84,
    diversity_inclusion_score: 0.86,
    worker_safety: 0.92,
    transparency_score: 0.69,
    corruption_risk: 0.54,
    board_diversity: 0.72,
    ethics_program: 0.74,
    compliance_systems: 0.72,
    quality_control_score: 0.87,
    supplier_diversity: 0.74,
    traceability: 0.64,
  },
];
