version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - MONGODB_URI=mongodb://mongo:27017/ethicsupply
      - CORS_ALLOWED_ORIGINS=http://localhost:5174,http://127.0.0.1:5174
    depends_on:
      - mongo
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
