services:
  # Django backend service
  - type: web
    name: optiethic-backend
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: |
      export PYTHONUNBUFFERED=1
      gunicorn ethicsupply.wsgi:application --log-level debug --access-logfile - --error-logfile -
    envVars:
      - key: DEBUG
        value: True
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://optiethic-frontend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: optiethic-db
          property: connectionString
      - key: DISABLE_COLLECTSTATIC
        value: 1
      - key: PYTHONUNBUFFERED
        value: 1

databases:
  - name: optiethic-db
    databaseName: optiethic
    plan: free
