# Docs for the Azure Web Apps Deploy action:
# https://github.com/Azure/webapps-deploy

name: Build and deploy Node.js app to Azure Web App - optisupply-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: optisupply-api
  AZURE_WEBAPP_PACKAGE_PATH: ethicsupply-node-backend
  NODE_VERSION: '22.x'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Build and test
        run: |
          npm run build --if-present
          npm run test --if-present
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3464204126BD47568E664423A0EF19C0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_95215755DE56484E91A5739D276AB6D8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A65E575D49B44C7B8DE9E7B6AF9038E5 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: Production
          package: .
